language: java

jdk:
  - oraclejdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "codesorcery-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
